//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TestDrawPic.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DPFTYPE                     130
#define ID_WINDOW_MANAGER               131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_MENU_POPUP                  310
#define IDD_BASEDIALOG                  313
#define IDR_TOOLBAR_EDIT_ZONE           316
#define IDR_DOCK_SELECT                 318
#define IDR_DOCK_PROPERTY               319
#define IDR_DOCK_LAYER                  320
#define IDR_VIEW_SUBVIEWER              321
#define IDD_DLG_SHADER                  326
#define IDD_DLG_PIC_REF_SIZE            327
#define IDD_DLG_ROOMLAYOUT_PICTURE_SIZE 327
#define IDD_DLG_ROOMLAYOUT_DRAWLINEINFO 328
#define IDD_DLG_ROOMLAYOUT_WALLPROPERTY 329
#define IDD_DLG_ROOMLAYOUT_DOORPROPERTY 330
#define IDD_DLG_ROOMLAYOUT_WINDOWPROPERTY 331
#define IDD_DLG_ROOMLAYOUT_ROOMPROPERTY 332
#define IDD_DLG_ROOMLAYOUT_PILLAR_PROPERTY 333
#define IDD_DIALOG1                     334
#define IDD_DLG_HTML_PAGE_NC            334
#define IDC_PROP_OBJ                    1003
#define IDC_SLIDER1                     1019
#define IDC_SLIDER2                     1020
#define IDC_SLIDER3                     1021
#define IDC_SLIDER4                     1022
#define IDC_SLIDER5                     1023
#define IDC_TXT_VALUE_1                 1024
#define IDC_TXT_VALUE_2                 1025
#define IDC_TXT_VALUE_3                 1026
#define IDC_TXT_VALUE_4                 1027
#define IDC_TXT_VALUE_5                 1028
#define IDC_TXT_MIN_1                   1029
#define IDC_TXT_MAX_1                   1030
#define IDC_TXT_MIN_2                   1031
#define IDC_TXT_PIC_REF_SIZE_NUM        1031
#define IDC_TXT_MAX_2                   1032
#define IDC_EDIT1                       1032
#define IDC_TXT_NUM                     1032
#define IDC_EDIT_WIDTH                  1032
#define IDC_EDIT_NAME                   1032
#define IDC_TXT_MIN_3                   1033
#define IDC_TXT_MAX_3                   1034
#define IDC_TXT_MIN_4                   1035
#define IDC_TXT_THICKNESS_NUM           1035
#define IDC_TXT_MAX_4                   1036
#define IDC_TXT_THICKNESS_NUM2          1036
#define IDC_TXT_HEIGHT_NUM              1036
#define IDC_TXT_MIN_5                   1037
#define IDC_BTN_MOVE                    1037
#define IDC_TXT_MAX_5                   1038
#define IDC_BTN_DELETE                  1038
#define IDC_EDIT_HEIGHT                 1039
#define IDC_EDIT_DEPTH                  1040
#define IDC_EDIT_OFFSETHEIGHT           1041
#define ID_BTN_OK                       1042
#define ID_BTN_CANCEL                   1043
#define IDC_BUTTON2                     1049
#define IDC_RADIO_LEFTOPEN              1050
#define IDC_RADIO_RIGHTOPEN             1051
#define IDC_BUTTON1                     1052
#define IDC_BTN_ROTATION                1052
#define IDC_RADIO_ALIGN_CEILING         1053
#define IDC_RADIO2                      1054
#define IDC_RADIO_ALIGN_FLOOR           1054
#define IDC_LBL_SPLASH                  1055
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BTN_VIEW_TOP                 32774
#define ID_BTN_CREATE_ROOM_AUTO         32775
#define ID_BTN_VIEW_RENDER              32777
#define ID_SUB_MENU_PROPERTY            32779
#define ID_EDIT_AREA                    32780
#define ID_BTN_CREATE_WALL_RECT         32781
#define ID_BTN_CREATE_ROOM_STYLE        32782
#define ID_BTN_CREATE_BEAM_LINE         32783
#define ID_BTN_CREATE_BEAM_RECT         32784
#define ID_BTN_CREATE_PILLAR_RECT       32785
#define ID_BTN_VIEW_SHOW                32787
#define ID_BTN_VIEW_HIDE                32788
#define ID_BTN_VIEW_FRONT               32789
#define ID_BTN_SETTING_DEFAULT          32791
#define ID_BTN_ORDER_NEW                32792
#define ID_BTN_ORDER_SAVE               32793
#define ID_BTN_ORDER_LIST_LOCAL         32794
#define ID_BTN_EDIT_WALL_SKIN           32795
#define ID_BTN_EDIT_WALL_ZONE           32797
#define ID_BTN_EDIT_FLOOR_ZONE          32798
#define ID_BTN_ORDER_DESIGN_NEW         32806
#define ID_BTN_EDIT_ZONE_CUT            32810
#define ID_BTN_EDIT_ZONE_RECT           32812
#define ID_BTN_STATE                    32823
#define ID_BUTTON2                      32824
#define ID_BTN_ROOMLAYOUT_TEST_PLILLAR  32824
#define ID_BTN_VIEW_ZERO                32825
#define ID_BTN_ROOMLAYOUT_PICTURE_SETSCALE 32826
#define ID_BTN_ROOMLAYOUT_TEST_DOOR     32827
#define ID_BTN_ROOMLAYOUT_PICTURE_PICTURE 32828
#define ID_BTN_ROOMLAYOUT_CREATE_DRAWWALL 32829
#define ID_BTN_ROOMLAYOUT_CREATE_DRAWROOM 32830
#define ID_CHK_ROOMLAYOUT_PICTURE_SHOW  32831
#define ID_BUTTON4                      32832
#define ID_SLIDE_ROOMLAYOUT_PICTURE_ALPHA 32833
#define ID_BUTTON3                      32835
#define ID_BTN_ROOMLAYOUT_PICTURE_SETPOSITION 32836
#define ID_BTN_ROOMLAYOUT_TEST_WINDOW   32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
